# Generated by Django 2.1 on 2018-08-23 16:48

from django.db import migrations

def forwards_func(apps, schema_editor):
    League = apps.get_model("leagues", "League")
    db_alias = schema_editor.connection.alias
    new_league = League.objects.using(db_alias).create(league_name='Default League')

    Team = apps.get_model("leagues", "Team")
    teams = Team.objects.using(db_alias).all()
    for team in teams:
        team.league = new_league
        team.save()


def reverse_func(apps, schema_editor):
    League = apps.get_model("leagues", "League")
    db_alias = schema_editor.connection.alias
    # This is a BAD THING because we accidentally wipe the teams table due to the CASCADE delete annotation in models
    League.objects.all().delete()

    Team = apps.get_model("leagues", "Team")
    teams = Team.objects.using(db_alias).all()
    for team in teams:
        team.league = None
        team.save()

class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20180823_1645'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
